### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Asel348**

### CODE REVIEW

**Comment by Asel348** [comment]
If there's a disclaimer, do I need to translate that too?

**Comment by Asel348** [comment]
If there's a disclaimer, does it needs to be translated too?

**Comment by LobbyDivinus** [comment]
What do you mean by disclaimer?

**Comment by Asel348** [comment]
In line 1411, it says "By enabling gameplay upload you allow us to upload your gameplay to our servers. See the disclaimer for more information". I mean, do I need to translate the disclaimer?

**Comment by LobbyDivinus** [comment]
It's up to you to decide about that. Either way is fine I think :)

**Pull request merged**
